# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robotoff/protos/product.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='robotoff/protos/product.proto',
  package='robotoff.protos',
  syntax='proto2',
  serialized_pb=_b('\n\x1drobotoff/protos/product.proto\x12\x0frobotoff.protos\"\xb5\x01\n\x07Product\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x16\n\x0e\x63ountries_tags\x18\x02 \x03(\t\x12\x17\n\x0f\x63\x61tegories_tags\x18\x03 \x03(\t\x12\x16\n\x0e\x65mb_codes_tags\x18\x04 \x03(\t\x12\x13\n\x0blabels_tags\x18\x05 \x03(\t\x12\x13\n\x0b\x62rands_tags\x18\x06 \x03(\t\x12\x10\n\x08quantity\x18\x07 \x01(\t\x12\x17\n\x0f\x65xpiration_date\x18\x08 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PRODUCT = _descriptor.Descriptor(
  name='Product',
  full_name='robotoff.protos.Product',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='robotoff.protos.Product.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='countries_tags', full_name='robotoff.protos.Product.countries_tags', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='categories_tags', full_name='robotoff.protos.Product.categories_tags', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='emb_codes_tags', full_name='robotoff.protos.Product.emb_codes_tags', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='labels_tags', full_name='robotoff.protos.Product.labels_tags', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brands_tags', full_name='robotoff.protos.Product.brands_tags', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='robotoff.protos.Product.quantity', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expiration_date', full_name='robotoff.protos.Product.expiration_date', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=232,
)

DESCRIPTOR.message_types_by_name['Product'] = _PRODUCT

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), dict(
  DESCRIPTOR = _PRODUCT,
  __module__ = 'robotoff.protos.product_pb2'
  # @@protoc_insertion_point(class_scope:robotoff.protos.Product)
  ))
_sym_db.RegisterMessage(Product)


# @@protoc_insertion_point(module_scope)
